name: Packer build

on:
  push:
    branches:
      - linuxupdates

jobs:
  build:
    runs-on: macos-latest
    steps:
      - name: checkout repo
        uses: actions/checkout@v4

      - name: Install parallels
        run: brew install parallels